[package]
edition = "2024"
name = "macro_env"
publish = false
version = "0.1.0"

[features]
frontend_url = ["dep:url"]
strum = ["dep:strum"]

[dependencies]
macro_env_var = { path = "../macro_env_var" }
serde = { workspace = true }
strum = { workspace = true, features = ["derive"], optional = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true, optional = true }
