[package]
edition = "2024"
name = "worker_trigger"
publish = false
version = "0.1.0"

[features]
local = []

[dependencies]
anyhow = { workspace = true }
aws-config = { workspace = true }
aws-sdk-ecs = "1.67.1"
aws_lambda_events = { workspace = true, features = ["eventbridge"] }
lambda_runtime = { workspace = true }
macro_entrypoint = { path = "../macro_entrypoint" }
macro_env = { path = "../macro_env" }
mockall = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
