[package]
edition = "2024"
name = "models_soup"
publish = false
version = "0.1.0"

[features]
mock = []
schema = ["dep:utoipa"]

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
macro_user_id = { path = "../macro_user_id" }
model-entity = { path = "../model-entity" }
models_pagination = { path = "../models_pagination" }
serde = { workspace = true }
strum = { workspace = true }
utoipa = { workspace = true, optional = true }
uuid = { workspace = true }
