[package]
name = "table-cleanup-handler"
version = "0.1.0"
edition = "2021"
rust-version = "1.79.0"
exclude = ["tests/", "fixtures/", "migrations/"]

[dependencies]
aws_lambda_events = { version = "0.15.0", default-features = false, features = ["eventbridge"] }

sqlx = { version = "0.8.1", features = ["runtime-tokio", "postgres", "uuid", "chrono"] }
lambda_runtime = "0.11.1"
tokio = { version = "1", features = ["macros"] }
serde = {version = "1.0.195", features = ["derive"]}
serde_json = "1.0.94"
dotenv = "0.15.0"
anyhow = "1.0.82"
