[package]
edition = "2024"
name = "serde_utils"
publish = false
version = "0.1.0"

[features]
urlencode = ["dep:urlencoding"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
urlencoding = { version = "2", optional = true }

[dev-dependencies]
cool_asserts = "2"
serde_urlencoded = { version = "0.7" }
url = { workspace = true, features = ["serde"] }
