[package]
edition = "2024"
exclude = ["examples/"]
name = "opensearch_client"
publish = false
version = "0.1.0"

[dev-dependencies]
chrono = { workspace = true }
macro_entrypoint = { path = "../macro_entrypoint" }
tokio = { workspace = true }
uuid = { workspace = true }


[dependencies]
anyhow = { workspace = true }
opensearch = { version = "2.3.0" }
opensearch_query_builder = { version = "0.2.1", default-features = false }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
unicode-segmentation = "1.9.0"
strum = { workspace = true }
