[package]
edition = "2024"
name = "static_file_service"
publish = false
version = "0.1.0"

[features]
dynamodb_client_test = []
local_auth = []
tree_trace = []

[dependencies]
anyhow = { workspace = true }
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-sdk-secretsmanager = { workspace = true }
aws-sdk-sqs.workspace = true
axum = { workspace = true, features = ["tower-log", "ws"] }
chrono = { workspace = true }
macro_auth = { path = "../macro_auth" }
macro_cors = { path = "../macro_cors" }
macro_entrypoint = { path = "../macro_entrypoint" }
macro_env = { path = "../macro_env" }
macro_middleware = { path = "../macro_middleware", default-features = false, features = [
  "auth",
] }
model = { path = "../model" }
models_sfs = { path = "../models_sfs" }
secretsmanager_client = { path = "../secretsmanager_client" }
serde = { workspace = true }
serde_dynamo = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true, features = ["limit", "timeout"] }
tracing.workspace = true
tracing-tree = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true, features = ["axum"] }
uuid.workspace = true
