[package]
edition = "2024"
name = "upload_extractor_lambda_trigger"
publish = false
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
aws-config = { workspace = true }
aws-sdk-sqs = { workspace = true }
aws_lambda_events = { workspace = true, features = ["eventbridge", "s3"] }
dynamodb_client = { path = "../dynamodb_client" }
lambda_runtime = { workspace = true }
macro_entrypoint = { path = "../macro_entrypoint" }
models_bulk_upload = { path = "../models_bulk_upload" }
openssl = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqs_client = { path = "../sqs_client" }
tokio = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["openssl"]
