[package]
edition = "2024"
name = "metering_service"
publish = false
version = "0.1.0"

[dependencies]
ai = { path = "../ai", default-features = false }
anyhow = { workspace = true }
axum = { workspace = true, features = ["tower-log"] }
chrono = { workspace = true }
macro_cors = { path = "../macro_cors" }
macro_entrypoint = { path = "../macro_entrypoint" }
macro_middleware = { path = "../macro_middleware", default-features = false, features = [
  "auth",
] }
metering_db_client = { path = "../metering_db_client/" }
remote_env_var = { path = "../remote_env_var" }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, features = [
  "chrono",
  "postgres",
  "runtime-tokio-rustls",
  "uuid",
] }
tokio = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true, features = ["axum_extras", "chrono", "uuid"] }
utoipa-swagger-ui = { workspace = true, features = ["axum"] }

[dev-dependencies]
axum-test = "15.0"
