[package]
edition = "2024"
name = "models_pagination"
publish = false
version = "0.1.0"

[features]
axum = ["dep:axum", "dep:model-error-response"]
docs = [
] # adds the doc attrs, the reason this is a feature is because of JsonSchema

[dependencies]
axum = { workspace = true, optional = true }
base64 = { workspace = true }
chrono = { workspace = true }
model-error-response = { path = "../model-error-response", optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
