[package]
edition = "2024"
name = "upload_extractor_lambda_handler"
publish = false
version = "0.1.0"

[features]
local = []

[dependencies]
anyhow = { workspace = true }
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-sdk-sqs = { workspace = true }
aws_lambda_events = { workspace = true, features = ["sqs"] }
chrono = { workspace = true }
connection_gateway = { path = "../connection_gateway" }
document_storage_service_client = { path = "../document_storage_service_client" }
dynamodb_client = { path = "../dynamodb_client" }
futures = { workspace = true }
lambda_runtime = { workspace = true }
macro_entrypoint = { path = "../macro_entrypoint" }
model = { path = "../model" }
model-entity = { path = "../model-entity" }
models_bulk_upload = { path = "../models_bulk_upload" }
openssl = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sqs_client = { path = "../sqs_client" }
tempfile = "3.19.1"
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
walkdir = "2.3.2"
zip = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["connection_gateway", "openssl"]
