[package]
edition = "2024"
name = "macro_db_client"
publish = false
version = "0.1.0"

[features]
account_merge_request = ["dep:rand"]
default = ["account_merge_request", "team"]
team = ["dep:models_team"]

[dependencies]
ai = { path = "../ai" }
anyhow = { workspace = true }
async-recursion = "1.1.1"
async-trait = { workspace = true }
cached = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
macro_uuid = { path = "../macro_uuid" }
mockall = { workspace = true }
model = { path = "../model" }
model-entity = { path = "../model-entity" }
models_dcs = { path = "../models_dcs" }
models_pagination = { path = "../models_pagination" }
models_permissions = { path = "../models_permissions" }
models_search = { path = "../models_search" }
models_soup = { path = "../models_soup" }
models_team = { path = "../models_team", optional = true }
rand = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
user_quota = { path = "../user_quota" }
macro_user_id = { path = "../macro_user_id" }
