[package]
edition = "2024"
name = "sha_cleanup_worker"
publish = false
version = "0.1.0"

[features]
local = []
redis_client_test = []

[dependencies]
anyhow = { workspace = true }
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
futures = { workspace = true }
macro_entrypoint = { path = "../macro_entrypoint" }
macro_env = { path = "../macro_env" }
mockall = { workspace = true }
redis = { workspace = true, features = [
  "cluster-async",
  "tokio-native-tls-comp",
] }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
