[package]
edition = "2024"
name = "models_search"
publish = false
version = "0.1.0"

[dependencies]
chrono = { workspace = true }
item_filters = { path = "../item_filters" }
opensearch_client = { path = "../opensearch_client" }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
utoipa = { workspace = true }
