[package]
edition = "2024"
name = "models_permissions"
publish = false
version = "0.1.0"

[dependencies]
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
strum = { workspace = true }
utoipa = { workspace = true }
