[package]
edition = "2024"
name = "sync_service_client"
publish = false
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
model = { path = "../model" }
reqwest = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
