[package]
default-run = "properties_service"
edition = "2024"
name = "properties_service"
publish = false
version = "0.1.0"

[lib]
name = "properties_service"
path = "src/lib.rs"

[[bin]]
name = "properties_service"
path = "src/main.rs"
required-features = []


[features]
default = ["postgres"]
local_auth = []
tree_trace = []
postgres = []
mock = ["dep:mockall"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
aws-config = { workspace = true }
aws-sdk-secretsmanager = { workspace = true }
axum = { workspace = true, features = ["tower-log", "ws"] }
chrono = { workspace = true }
comms_service_client = { path = "../comms_service_client" }
http-body-util = { workspace = true }
macro_auth = { path = "../macro_auth" }
macro_cors = { path = "../macro_cors" }
macro_entrypoint = { path = "../macro_entrypoint" }
macro_env = { path = "../macro_env" }
macro_middleware = { path = "../macro_middleware", default-features = false, features = [
  "auth",
  "cloud_storage",
] }
macro_uuid = { path = "../macro_uuid" }
mockall = { workspace = true, optional = true }
model = { path = "../model" }
models_permissions = { path = "../models_permissions" }
models_properties = { path = "../models_properties" }
secretsmanager_client = { path = "../secretsmanager_client" }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-tree = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true, features = ["axum"] }
uuid = { workspace = true }
