[package]
edition = "2024"
name = "models_metering"
publish = false
version = "0.1.0"

[dependencies]
ai = { path = "../ai", default-features = false }
chrono = { workspace = true }
derive_builder = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, features = [
  "chrono",
  "postgres",
  "runtime-tokio-rustls",
  "uuid",
] }
utoipa = { workspace = true, features = ["axum_extras", "chrono", "uuid"] }
uuid = { workspace = true }
