[package]
edition = "2024"
name = "test_pdf_modification_data_deserialize"
publish = false
version = "0.1.0"

[[bin]]
name = "test_placeable_thread_deserialization"

[[bin]]
name = "test_highlight_deserialization"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
model = { path = "../../model" }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
