[package]
edition = "2024"
name = "gmail_client"
publish = false
version = "0.1.0"

[features]
gmail_test = []

[dependencies]
ammonia = "4.1.0"
anyhow = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
jsonwebtoken = { workspace = true }
mail-builder = "0.4.3"
mailparse = "0.16.1"
mockall = { workspace = true }
models_email = { path = "../models_email" }
once_cell = { workspace = true }
reqwest = { workspace = true, features = ["stream"] }
scraper = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
