[package]
edition = "2024"
name = "model_notifications"
publish = false
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
model-entity = { path = "../model-entity" }
models_comms = { path = "../models_comms" }
models_pagination = { path = "../models_pagination" }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
strum = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
utoipa = { workspace = true }
uuid = { workspace = true }
