[package]
name = "jobs-handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
job_types = { path = "../job_types" }
aws-config = "1.2.1"
aws-sdk-dynamodb = "1.23.0"
lambda_http = "0.11.1"
lazy_static = "1.4.0"
tokio = { version = "1", features = ["macros"] }
serde = {version = "1.0.195", features = ["derive"]}
serde_json = "1.0.94"
serde_dynamo = { version = "4", features = ["aws-sdk-dynamodb+1"] }
chrono = { version = "0.4.38", features = ["serde"]}
uuid = { version = "1.8.0", features = ["v4", "fast-rng"] }
anyhow = "1.0.82"
aws-sdk-apigatewaymanagement = "1.21.0"
reqwest = { version = "0.12", features = ["json","rustls-tls"], default-features=false }
rustls = "0.23.5"
lambda_runtime = "0.11.1"
