[package]
edition = "2024"
name = "organization_service"
publish = false
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
aws-config = { workspace = true }
aws-sdk-secretsmanager = { workspace = true }
aws-sdk-sesv2 = { workspace = true }
axum = { workspace = true, features = ["tower-log"] }
http-body-util = { workspace = true }
lazy_static = { workspace = true }
macro_auth = { path = "../macro_auth" }
macro_cors = { path = "../macro_cors" }
macro_db_client = { path = "../macro_db_client" }
macro_entrypoint = { path = "../macro_entrypoint" }
macro_env = { path = "../macro_env" }
macro_env_var = { path = "../macro_env_var" }
macro_middleware = { path = "../macro_middleware", default-features = false, features = [
  "auth",
  "user_permissions",
] }
model = { path = "../model" }
models_permissions = { path = "../models_permissions" }
redis = { workspace = true, features = ["tokio-native-tls-comp"] }
regex = { workspace = true }
reqwest = { workspace = true }
secretsmanager_client = { path = "../secretsmanager_client" }
serde = { workspace = true }
serde_json = { workspace = true }
ses_client = { path = "../ses_client" }
sqlx = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true, features = ["util"] }
tower-http = { workspace = true }
tracing = { workspace = true }
urlencoding = { workspace = true }
utoipa = { workspace = true, features = ["axum_extras"] }
utoipa-swagger-ui = { workspace = true, features = ["axum"] }
