[package]
edition = "2024"
name = "unfurl_service"
publish = false
version = "0.1.0"

[features]
mock = []

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
futures = { workspace = true }
http = "1.3.1"
http-body-util = { workspace = true }
macro_cors = { path = "../macro_cors" }
macro_entrypoint = { path = "../macro_entrypoint" }
macro_env = { path = "../macro_env" }
reqwest = { workspace = true, features = ["stream"] }
scraper = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
utoipa = { workspace = true, features = ["axum_extras", "chrono", "uuid"] }
utoipa-swagger-ui = { workspace = true, features = ["axum"] }
