[package]
edition = "2024"
name = "test_build_full_pdf_modification_data"
publish = false
version = "0.1.0"

[[bin]]
name = "main"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
macro_db_client = { path = "../../macro_db_client" }
macro_entrypoint = { path = "../../macro_entrypoint" }
model = { path = "../../model" }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
