[package]
edition = "2024"
name = "model"
publish = false
version = "0.1.0"

[[bin]]
name = "generate_typescript_types"
path = "src/bin/generate_typescript_types.rs"

[dependencies]
ai = { path = "../ai" }
ai_format = { path = "../ai_format" }
anyhow = { workspace = true }
axum = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
model-error-response = { path = "../model-error-response" }
model_user = { path = "../model_user" }
models_bulk_upload = { path = "../models_bulk_upload" }
models_comms = { path = "../models_comms" }
models_email = { path = "../models_email" }
models_pagination = { path = "../models_pagination" }
models_permissions = { path = "../models_permissions" }
model_file_type = { path = "../model_file_type" }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["raw_value"] }
serde_repr = { workspace = true }
serde_with = { workspace = true }
sqlx = { workspace = true }
strum = { workspace = true }
thiserror.workspace = true
tracing = { workspace = true }
utoipa = { workspace = true, features = ["axum_extras", "chrono"] }
uuid = { workspace = true }
