[package]
edition = "2024"
name = "search_upload_handler"
publish = false
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
aws-config = { workspace = true }
aws-sdk-sqs = { workspace = true }
aws_lambda_events = { workspace = true, features = ["eventbridge"] }
lambda_runtime = { workspace = true }
macro_entrypoint = { path = "../macro_entrypoint" }
model_file_type = { path = "../model_file_type" }
openssl = { workspace = true }
sqs_client = { path = "../sqs_client", default-features = false, features = [
  "search",
] }
tokio = { workspace = true }
urlencoding = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["openssl"]
