[package]
edition = "2024"
exclude = ["examples/"]
name = "macro_notify"
publish = false
version = "0.1.0"

[features]
local_queue = []

[dependencies]
anyhow = { workspace = true }
aws-config = { workspace = true }
aws-sdk-sqs = { workspace = true }
macro_uuid = { path = "../macro_uuid" }
model = { path = "../model" }
model_notifications = { path = "../model_notifications" }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
