[package]
edition = "2024"
name = "macro_user_id"
publish = false
version = "0.1.0"

[dependencies]
doppleganger = { workspace = true }
nom = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
