[package]
edition = "2024"
name = "models_email"
publish = false
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
ego-tree = { workspace = true }
html2text = "0.15.1"
lazy_static = { workspace = true }
macro_uuid = { path = "../macro_uuid" }
models_pagination = { path = "../models_pagination" }
regex = { workspace = true }
schemars = { workspace = true }
scraper = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["raw_value"] }
serde_with = { workspace = true }
sqlx = { workspace = true }
strum = { workspace = true }
thiserror.workspace = true
utoipa = { workspace = true, features = ["axum_extras", "chrono"] }
uuid = { workspace = true }
