[package]
edition = "2024"
exclude = ["examples/"]
name = "macro_share_permissions"
publish = false
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
comms_service_client = { path = "../comms_service_client" }
macro_db_client = { path = "../macro_db_client" }
model = { path = "../model" }
model-entity = { path = "../model-entity" }
model_notifications = { path = "../model_notifications" }
models_permissions = { path = "../models_permissions" }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
