[package]
edition = "2024"
name = "search_service"
publish = false
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
aws-config = { workspace = true }
aws-sdk-secretsmanager = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
comms_service_client = { path = "../comms_service_client" }
document_storage_service_client = { path = "../document_storage_service_client" }
email_service_client = { path = "../email_service_client" }
futures = { workspace = true }
http-body-util = { workspace = true }
macro_auth = { path = "../macro_auth" }
macro_db_client = { path = "../macro_db_client" }
macro_cors = { path = "../macro_cors" }
macro_entrypoint = { path = "../macro_entrypoint" }
macro_env = { path = "../macro_env" }
macro_middleware = { path = "../macro_middleware", default-features = false, features = [
    "auth",
] }
model = { path = "../model" }
models_email = { path = "../models_email" }
models_search = { path = "../models_search" }
opensearch_client = { path = "../opensearch_client" }
secretsmanager_client = { path = "../secretsmanager_client" }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
item_filters = { path = "../item_filters" }
thiserror = { workspace = true }

[dev-dependencies]
macro_auth = { path = "../macro_auth", features = ["testing"] }
