[package]
edition = "2024"
name = "saved_views"
publish = false
version = "0.1.0"

[dependencies]
chrono = { workspace = true }
macro_uuid = { path = "../macro_uuid" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true, features = ["uuid"] }
uuid = { workspace = true }
