[package]
edition = "2024"
name = "model_user"
publish = false
version = "0.1.0"

[features]
axum = ["dep:axum", "dep:thiserror"]

[dependencies]
axum = { workspace = true, optional = true }
macro_user_id = { path = "../macro_user_id" }
serde = { workspace = true }
thiserror = { workspace = true, optional = true }
utoipa = { workspace = true }
uuid = { workspace = true }
